////////


#cmakedefine01 INCLUDE__NRF5SDK_EXTENSION

#if (INCLUDE__NRF5SDK_EXTENSION == 1)

#define NRF5SDK__DTTY_NRF_ISR_WRITE_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_ISR_WRITE_BUFFER_SIZE@)

#define NRF5SDK__DTTY_NRF_UART_READ_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_UART_READ_BUFFER_SIZE@)
#define NRF5SDK__DTTY_NRF_UART_WRITE_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_UART_WRITE_BUFFER_SIZE@)

#define NRF5SDK__DTTY_NRF_LIBUARTE_READ_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_LIBUARTE_READ_BUFFER_SIZE@)
#define NRF5SDK__DTTY_NRF_LIBUARTE_WRITE_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_LIBUARTE_WRITE_BUFFER_SIZE@)

#define NRF5SDK__DTTY_NRF_BLE_UART_READ_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_BLE_UART_READ_BUFFER_SIZE@)
#define NRF5SDK__DTTY_NRF_BLE_UART_WRITE_BUFFER_SIZE (@NRF5SDK__DTTY_NRF_BLE_UART_WRITE_BUFFER_SIZE@)

#endif /* (INCLUDE__NRF5SDK_EXTENSION == 1) */

